USE [master]
GO

/****** Object:  Database [Scheduling]    Script Date: 19/09/2016 20:10:19 ******/
CREATE DATABASE [Scheduling]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Scheduling', FILENAME = N'D:\SQLSERVER\MSSQL13.MSSQLSERVER\MSSQL\DATA\Scheduling.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Scheduling_log', FILENAME = N'D:\SQLSERVER\MSSQL13.MSSQLSERVER\MSSQL\DATA\Scheduling.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Scheduling] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Scheduling].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Scheduling] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Scheduling] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Scheduling] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Scheduling] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Scheduling] SET ARITHABORT ON 
GO

ALTER DATABASE [Scheduling] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Scheduling] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Scheduling] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Scheduling] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Scheduling] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Scheduling] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Scheduling] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Scheduling] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Scheduling] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Scheduling] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Scheduling] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Scheduling] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Scheduling] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Scheduling] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Scheduling] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Scheduling] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Scheduling] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Scheduling] SET RECOVERY FULL 
GO

ALTER DATABASE [Scheduling] SET  MULTI_USER 
GO

ALTER DATABASE [Scheduling] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Scheduling] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Scheduling] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Scheduling] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Scheduling] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Scheduling] SET QUERY_STORE = OFF
GO

USE [Scheduling]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Scheduling] SET  READ_WRITE 
GO


USE [Scheduling]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Calculations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[A] [int] NOT NULL,
	[B] [int] NOT NULL,
	[Som] [int] NULL,
	[DateCreated] [datetime] NOT NULL,
	[DateProcessed] [datetime] NULL
) ON [PRIMARY]

GO

INSERT INTO [dbo].[Calculations]
           ([A]
           ,[B]
           ,[Som]
           ,[DateCreated]
           ,[DateProcessed])
     VALUES
           (5
           ,10
           ,NULL
           ,GETDATE()
           ,NULL)

INSERT INTO [dbo].[Calculations]
           ([A]
           ,[B]
           ,[Som]
           ,[DateCreated]
           ,[DateProcessed])
     VALUES
           (5
           ,-3
           ,NULL
           ,GETDATE()
           ,NULL)

INSERT INTO [dbo].[Calculations]
           ([A]
           ,[B]
           ,[Som]
           ,[DateCreated]
           ,[DateProcessed])
     VALUES
           (2
           ,5
           ,NULL
           ,GETDATE()
           ,NULL)

INSERT INTO [dbo].[Calculations]
           ([A]
           ,[B]
           ,[Som]
           ,[DateCreated]
           ,[DateProcessed])
     VALUES
           (8
           ,12
           ,NULL
           ,GETDATE()
           ,NULL)

INSERT INTO [dbo].[Calculations]
           ([A]
           ,[B]
           ,[Som]
           ,[DateCreated]
           ,[DateProcessed])
     VALUES
           (35
           ,324
           ,NULL
           ,GETDATE()
           ,NULL)
GO





USE [master]
GO

/****** Object:  Database [Hangfire]    Script Date: 21/09/2016 15:12:30 ******/
CREATE DATABASE [Hangfire]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Hangfire', FILENAME = N'D:\SQLSERVER\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hangfire.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Hangfire_log', FILENAME = N'D:\SQLSERVER\MSSQL13.MSSQLSERVER\MSSQL\DATA\Hangfire_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Hangfire] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Hangfire].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Hangfire] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Hangfire] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Hangfire] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Hangfire] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Hangfire] SET ARITHABORT OFF 
GO

ALTER DATABASE [Hangfire] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Hangfire] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Hangfire] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Hangfire] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Hangfire] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Hangfire] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Hangfire] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Hangfire] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Hangfire] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Hangfire] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Hangfire] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Hangfire] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Hangfire] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Hangfire] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Hangfire] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Hangfire] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Hangfire] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Hangfire] SET RECOVERY FULL 
GO

ALTER DATABASE [Hangfire] SET  MULTI_USER 
GO

ALTER DATABASE [Hangfire] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Hangfire] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Hangfire] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Hangfire] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Hangfire] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Hangfire] SET QUERY_STORE = OFF
GO

USE [Hangfire]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Hangfire] SET  READ_WRITE 
GO

